### ISSUE TITLE
文档中心的图片，能否支持点击放大？

### ISSUE THREAD

**Issue by zainosl** [LISTENAI/LSOpenWeb#22]
![image](https://user-images.githubusercontent.com/48555232/129135986-7c09c568-0911-472f-a2ce-3800c7e95596.png)
像这种图文并茂的文档，以后会越来越多，承载的信息比较多图片，如果不能放大，就比较难进行阅读。
希望可以增加文档中心图片点击放大的功能。

**Comment by monsterboom** [comment]
nicea

**Comment by listenai-open** [comment]
目前不支持放大

**Comment by listenai-open** [comment]
目前不支持放大

**Comment by listenai-open** [comment]
目前不支持放大

**Comment by listenai-open** [comment]
目前不支持放大
