### ISSUE TITLE
文档反馈：/AIsolution/ESR/softwaredevelopment/Basic_development/peripheral_config

### ISSUE THREAD

**Issue by CHN-KingMumu** [LISTENAI/LSOpenWeb#58]
[文档链接](https://docs.listenai.com/AIsolution/ESR/softwaredevelopment/Basic_development/peripheral_config) 
 问题描述：文档内容有误/与实际不符
文档链接：https://docs.listenai.com/AIsolution/ESR/softwaredevelopment/Basic_development/peripheral_config
![file](https://listenai-external.oss-cn-beijing.aliyuncs.com/public/doc_issues/f6f4f9cda5aa17a087e3bf7d895fa727.png)
![file](https://listenai-external.oss-cn-beijing.aliyuncs.com/public/doc_issues/f8e27880efa1486decf9176eb542f692.jpg)

**Comment by zainosl** [comment]
最新master已修改
