### ISSUE TITLE
需求： 汉化红框部分（可先做）

### ISSUE THREAD

**Issue by zainosl** [LISTENAI/LSOpenWeb#8]
![image](https://user-images.githubusercontent.com/48555232/127994737-fd596c97-0f34-44a8-8c28-e14abd370a1c.png)

**Comment by monsterboom** [comment]
在该commit已解决。
https://github.com/LISTENAI/LSOpenWeb/commit/e5613714d5fdc8e121969de566e20bae17b6459c
